base:
  mass: 0.8               # Base mass in Kg
  x_size: 0.14           # Dimension in x axis
  y_size: 0.08            # Dimension in y axis
  z_size: 0.03           # Dimension in z axis
  mesh: 'chassis.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''

jetson_deck:
  mass: 0.1               # Base mass in Kg
  x_size: 0.14           # Dimension in x axis
  y_size: 0.09            # Dimension in y axis
  z_size: 0.002           # Dimension in z axis
  mesh: 'deck/jetson_nano_deck.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

rpi_deck:
  mass: 0.1               # Base mass in Kg
  x_size: 0.14           # Dimension in x axis
  y_size: 0.09            # Dimension in y axis
  z_size: 0.002           # Dimension in z axis
  mesh: 'deck/raspberry_pi_deck.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

lidar_platform: # todo rearange
  mass: 0.05               # Lidar platform mass in kg
  x_size: 0.08             # Dimension in x axis
  y_size: 0.1              # Dimension in y axis
  z_size: 0.05             # Dimension in z axis
  mesh: 'lidar_platform/platfom_rplidar_a2.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

slamtec_holder:
  mass: 0.01                # Slamtec holder mass in kg
  x_size: 0.05              # Dimension in x axis
  y_size: 0.015             # Dimension in y axis
  z_size: 0.025             # Dimension in z axis
  mesh: 'lidar_platform/slamtec_holder.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

slamtec_usb_to_serial:
  mass: 0.01                # Base mass in Kg
  x_size: 0.05              # Dimension in x axis
  y_size: 0.015             # Dimension in y axis
  z_size: 0.025             # Dimension in z axis
  mesh: '../components/slamtec_rplidar_usb_to_serial.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

camera_mount:
  mass: 0.01               # Camera mount mass in kg
  x_size: 0.05             # Dimension in x axis
  y_size: 0.09             # Dimension in y axis
  z_size: 0.03             # Dimension in z axis
  mesh: 'camera_mount/camera_mount.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

raspi-cam:
  mass: 0.01                # Raspi cam mount mass in kg
  x_size: 0.03              # Dimension in x axis
  y_size: 0.065             # Dimension in y axis
  z_size: 0.025             # Dimension in z axis
  mesh: 'camera_mount/Raspberry_pi_CAM_holder.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

oak-1:
  mass: 0.01               # OAK-1 mount mass in kg
  x_size: 0.03             # Dimension in x axis
  y_size: 0.065            # Dimension in y axis
  z_size: 0.025            # Dimension in z axis
  mesh: 'camera_mount/OAK-1_adjustment_mount.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

oak-d:
  mass: 0.01               # OAK-D mass in kg
  x_size: 0.03             # Dimension in x axis
  y_size: 0.065            # Dimension in y axis
  z_size: 0.025            # Dimension in z axis
  mesh: 'camera_mount/OAK-D_adjustment_mount.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

breadboard:
  mass: 0.01                # Breadboard mass in kg
  x_size: 0.055             # Dimension in x axis
  y_size: 0.08              # Dimension in y axis
  z_size: 0.01              # Dimension in z axis
  mesh: '../components/breadboard_400_point.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

power_bank:
  mass: 0.1                # Power bank mass in kg
  x_size: 0.13             # Dimension in x axis
  y_size: 0.07             # Dimension in y axis
  z_size: 0.018             # Dimension in z axis
  mesh: '../components/power_bank.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

battery_pack:
  mass: 0.1                # Battery pack mass in kg
  x_size: 0.058            # Dimension in x axis
  y_size: 0.063            # Dimension in y axis
  z_size: 0.03             # Dimension in z axis
  mesh: '../components/battery_pack.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

mcu:
  mass: 0.01               # MCU mass in kg
  x_size: 0.04             # Dimension in x axis
  y_size: 0.02             # Dimension in y axis
  z_size: 0.01             # Dimension in z axis
  mesh: '../components/teensy_4-0.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  #mesh: ''
  scale: '0.001 0.001 0.001'

motor_driver:
  mass: 0.01               # Motor driver mass in kg
  x_size: 0.05             # Dimension in x axis
  y_size: 0.025            # Dimension in y axis
  z_size: 0.01             # Dimension in z axis
  mesh: '../components/adafruit_dc_stepper_featherwing.stl'  # Name of the mesh files. Leave it empty ('') to have a white base.
  mesh: ''
  scale: '0.001 0.001 0.001'